spring.application.name=backend

ai.internal-base-url=${AI_INTERNAL_BASE_URL:http://ai-service:8000}
ai.public-base-url=${AI_PUBLIC_BASE_URL:http://localhost:8000}
ai.azure-storage-connection-string=${AZURE_STORAGE_CONNECTION_STRING}
ai.azure-container-name=${AZURE_CONTAINER_NAME}
ai.use-blob-storage=${USE_BLOB_STORAGE:false}
image.token.secret=${IMAGE_TOKEN_SECRET:defaultSecretKeyForTokensIfEnvMissing}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB
