spring.application.name=backend

ai.internal-base-url=${AI_INTERNAL_BASE_URL:http://ai-service:8000}
ai.public-base-url=${AI_PUBLIC_BASE_URL:http://localhost:8000}
image.token.secret=${IMAGE_TOKEN_SECRET:defaultSecretKeyForTokensIfEnvMissing}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB
